### ISSUE TITLE
Hosted EDS implementation with AWS Cloud Map

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#11]
Details: AWS Cloud Map to act as cross-service service registry for service endpoints and metadata. ECS already integrates with Cloud Map and we plan to build EKS connector to Cloud Map.

**Comment by rimaulana** [comment]
Hi @jamsajones, any details on this? Is this trying to achieve the same thing as https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws-sd.md?

**Comment by shidel-dev** [comment]
@abby-fuller @jamsajones what got shipped here? This sounds like App Mesh now has a hosted EDS implementation, is this the case? Can I use my own static envoy config, and configure my clusters to use this hosted EDS?

**Comment by lavignes** [comment]
Hi @shidel-dev. Currently App Mesh does not have a dedicated EDS endpoint. We provide EDS as part of our ADS implementation by querying AWS Cloud Map for each discoverable backend Virtual Node. These approximately map 1:1 to clusters.

Depending on your use-case you may be able to have static clusters that get endpoints via our ADS. But since we don't provide a dedicated EDS endpoint you'll be pretty limited. And you'll still need to model your clusters as Virtual Nodes in App Mesh. 

e.g. Something similar to the [Mostly Static With Dynamic EDS example](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview#mostly-static-with-dynamic-eds):

envoy.yaml:
```
node:
    id: /mesh/$MESH_NAME/virtualNode/$VIRTUAL_NODE_NAME
    cluster: /mesh/$MESH_NAME/virtualNode/$VIRTUAL_NODE_NAME

dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.$AWS_REGION.amazonaws.com:443
        stat_prefix: ads
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
            config:
              region: $AWS_REGION
              service_name: appmesh
  lds_config: {ads: {}}
  # disable CDS: cds_config: {ads: {}}

static_resources:
  clusters:
    # Protocol and port must also match those of the target virtual node
  - name: cds_egress_${MESH_NAME}_${TARGET_VIRTUAL_NODE_NAME}_http_8080
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        ads: {}
```

Since we'd have to also disable CDS via ADS, you'd have to manually model each CDS resource statically. I haven't tried this but it seems like it would work. That said, this is not a robust solution, I think a dedicated EDS endpoint could be useful. Want to open a feature request and tell us your use-case more?
