### ISSUE TITLE
Allow multiple HTTP match headers conditions for a single route

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-roadmap#123]
Allow using multiple headers `OR` conditions. e.g. route Safari users or users with an `insider` cookie to the canary:

```yaml
routes:
- http:
    action:
      weightedTargets:
      - virtualNodeName: podinfo-canary
        weight: 100
    match:
      - headers:
        - name: cookie
          match:
            regex: "^(.*?;)?(type=insider)(;.*)?$"    
      - headers:
        - name: user-agent
          match:
            regex: "(?=.*Safari)(?!.*Chrome).*$"   
      - uri:
          prefix: "/"

**Comment by dfezzie** [comment]
Thanks @stefanprodan. I've gone ahead and transferred this issue to aws/app-mesh-roadmap since this is a general App Mesh feature request. In the future can you open feature requests here in this repository? Thanks again 👍

**Comment by lavignes** [comment]
Right now header matching is pretty much 1:1 with Envoy's API: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=strip%20headers#envoy-api-field-route-routematch-headers

It doesn't support any sort of inclusive-or matching right now. Perhaps we could expose some API to express inclusive-or matches at the route-level:

```
route:
  orMatch:
    - prefix: /
      - headers:
        match:
        - name: foo
          value: bar
    - prefix: /
      - headers:
        match:
        - name: baz
          value: qux
```

which could just be a short-hand for multiple identical routes. This is just me spit-balling. We'd need to think carefully about the ergonomics of this.

**Comment by stefanprodan** [comment]
@lavignes I think making the match an array of conditions would solve the issue without introducing operators like `orMatch`. 

E.g. target macOS users with a `canary=enabled` cookie or those with a `X-Canary` header:

```yaml
routes:
- http:
    action:
      weightedTargets:
      - virtualNodeName: podinfo-canary
        weight: 100
    match:
      - prefix: /
        headers:
        - name: user-agent
          match:
            regex: ".*Macintosh.*"
        - name: cookie
          match:
            regex: "^(.*?;)?(canary=enabled)(;.*)?$"    
      - prefix: /
        headers:
        - name: x-canary
          match:
            exact: "enabled"
```

**Comment by lavignes** [comment]
@stefanprodan Unfortunately, `match` is currently defined as an object in our API, not an array. Changing this has implications that affect our SDKs. So adding a new field is generally preferable from an api-compatibility perspective. Regardless, I appreciate this feature suggestion. I do see this as a situation that many people may run into.

**Comment by stefanprodan** [comment]
If I had to make such a change without breaking backwards compatibility in App Mesh CRD, I would create a type that accepts both an object or an array of objects e.g. `MatchOrMatchArray`

```yaml
openAPIV3Schema:
  properties:
    spec:
      properties:
        match:
          description: A HTTP match condition or array of conditions
          anyOf:
            - type: object
              properties:
                prefix:
                  description: URL prefix
                  type: string
            - type: array
              properties:
                items:
                  type: object
                  properties:
                    prefix:
                      description: URL prefix
                      type: string
```

I think this could easily be handled in the Virtual Service CRD, the App Mesh Kubernetes controller could take an array of conditions and create a route for each one in the App Mesh API.
