### ISSUE TITLE
Feature Request: Optional Cloud Map Attributes

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-roadmap#129]
A very useful feature would be the ability to select Cloud Map attributes on a virtual node that are optional. This would give preference to service instances that have said attributes, but allow for still matching on instances that match a minimum set of requirements.

For example: Today you can manually select ECS instances in a given AZ:

```
serviceDiscovery:
  awsCloudMap:
    attributes:
      - key: AVAILABILITY_ZONE
        value: us-east-1a
```

But if instances in that AZ are missing, there is no way to automatically fall-back to other instances in the region.

If we exposed some way to optionally **prefer** instances with particular attributes, then our desired behavior could be expressed something like:

```
serviceDiscovery:
  awsCloudMap:
    attributes:
      - key: AVAILABILITY_ZONE
        value: us-east-1a
        optional: true
```

Cloud Map's `DiscoverInstances` API does not have this feature though. It could be emulated by manually filtering/sorting for each optional attribute before distributing endpoints to Envoy. But it would make sense to try and get this as a first-class feature in Cloud Map as it is generally useful.
