### ISSUE TITLE
Feature Request: running App Mesh outside of docker

### ISSUE THREAD

**Issue by ddelnano** [aws/aws-app-mesh-roadmap#131]
**Tell us about your request**
Our current service mesh is agnostic to how workloads are run and integrates nicely with containerized and non containerized services. Because of this we have a large number of instances that do not have docker installed that use our service mesh. Our service mesh runs outside of docker even for containerized workloads (deployed on every EC2 instance bound to a network interface docker containers can access). As a result, App mesh's deployment, which recommends running a docker container, will not work well for our use case.

Since App mesh is changes on top of [envoy project](https://github.com/envoyproxy/envoy) that are planned to be upstreamed, it seems that it shouldn't be that difficult to make this possible once that occurs. We already package our own envoy and so if its configuration was documented this could probably solve our problem.

**Which integration(s) is this request for?**
EC2

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are looking to see if App mesh would work for our use case. It is hard because it would require installing docker on many instances that we don't want running docker. It could also mean that we would have to rearchitect how we deploy our service mesh (running container sidecars rather than deploying it one per host).

**Are you currently working around this issue?**
No. We are currently evaluating App mesh to see if it would work as a replacement for our current service mesh (smartstack).

**Comment by dastbe** [comment]
Hey @ddelnano!

We certainly support any compute target that you can throw an Envoy onto, though our documentation outside of ECS/k8s is sparse :(.

And while we haven't done much explicit documentation of our Envoy build/release/configuration, the mechanism for an Envoy connecting to App Mesh is very well standardized. We've [upstreamed](https://github.com/envoyproxy/envoy/pull/7532) support for using aws credentials to authenticate to our ADS endpoint, which will support all conventional forms of credential discovery. 

The minimum viable bootstrap configuration for an Envoy you'll need will look like

```
node:
    id: /mesh/$MESH_NAME/virtualNode/$VIRTUAL_NODE_NAME
    cluster: /mesh/$MESH_NAME/virtualNode/$VIRTUAL_NODE_NAME

dynamic_resources:
  # Configure Envoy to get listeners and clusters via GRPC ADS
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.$AWS_REGION.amazonaws.com:443
        stat_prefix: ads
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
            config:
              region: $AWS_REGION
              service_name: appmesh
  lds_config: {ads: {}}
  cds_config: {ads: {}}
```

Additionally, if you want to configure iptables to work as they when running on ECS or k8s, I would explore the following script in our proxy manager image that we use for deploying to k8s

```
docker run -it --rm --entrypoint cat 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v2 bin/sidecar-proxy-route-manager.sh
```
