### ISSUE TITLE
Bug: Unable to set route target weight to 0 in CloudFormation only

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#133]
**Summary**
When setting up a Route resource in a CloudFormation template, you cannot set the weight of a given target within the route to zero. You can set the target weight to zero through the CLI, console, and SDKs.

**Steps to Reproduce**

1. Create a CloudFormation template with an App mesh Route resource that uses 0 for a target weight, for example:
```
Resources:
  MyRoute:
    Type: "AWS::AppMesh::Route"
    Properties:
      RouteName: my-route
      MeshName: my-mesh
      VirtualRouterName: my-virtual-router
      Spec:
        TcpRoute:
          Action:
            WeightedTargets:
            - VirtualNode: vn1
              Weight: 10
            - VirtualNode: vn2
              Weight: 0
```

**Expected**: You can create the route with a weight of 0 for vn2.
**Actual**: Deploying the template fails due to a validation error.

**Are you currently working around this issue?**

You can work around the issue by removing the target from the route, however we understand that customers may just want to set the weight to zero.
