### ISSUE TITLE
Feature Request: External Authorization Support

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#140]
**Tell us about your request**

Once a client has been identified (e.g. via a certificate, request token, or IP address), it would be useful to perform an authorization check to further restrict the scope of access to a given service. For example, restricting certain identified clients to only specific HTTP verbs and paths.

Envoy supports authorizing a client using an [external authorization provider](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto), which allows you to bring an existing solution in (such as [Open Policy Agent](https://www.openpolicyagent.org/)), or write your own.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
After identifying a caller, there is a need to further restrict access to an endpoint such that only certain actions may be performed. Authorization can be performed on HTTP for example by only allowing GET requests on specific paths.

Being able to authorize a client through a separate application provides a flexible interface that can be customized to fit many needs.

**Are you currently working around this issue?**
This issue can be worked around by implementing authorization in the application code, or some other middle hop, but represents additional complexity that doesn't fit the primary benefits and uses of a service mesh.

**Comment by abhijitherekar** [comment]
hi @bcelenza , is there a open PR for this? Would be really interested to check this feature. 
Please, let me know.

**Comment by lavignes** [comment]
Hey @abhijitherekar. We're still currently researching how we'll implement this feature in App Mesh. We'll update this issue when we have an API proposal and will happily accept feedback / answer any questions you post here.

**Comment by bcelenza** [comment]
Hey folks!

We're working on this feature, and looking for your input. 5 easy questions below -- please feel free to answer any that pertain to your needs.

1. Do you require authorization capabilities for traffic coming from outside your mesh, within your mesh, or both?
2. What types of identities do you need to perform an authorization decision on (e.g. X.509 certificate, OAuth bearer token, JWT), and where within (or outside) of the mesh do you use them?
3. For services within the mesh, do your authorization policies vary greatly from service to service, or are they largely the same?
4. Is the component making the authorization decision a local process (i.e. sidecar) or a remote service? If remote, is the service within or outside of the mesh configuration.
5. Do you plan on using an existing solution that integrates with Envoy's external authorization API (e.g. Open Policy Agent)? If not, what solution would you ideally like to use?

Thanks in advance!

**Comment by RyanFrench** [comment]
Hi Brian.

My team is currently considering migrating to AppMesh, but we would require this feature before we could use the Virtual Gateway for ingress to the mesh. Our requirement is for an auth subrequest for ingress traffic, similar to how the [NGINX auth subrequest](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/) works. To provide this capability we have been looking at running our own Envoy or NGINX service that has an Envoy sidecar so that it can proxy requests to services within the mesh.

1. We would only require this for traffic coming from outside the mesh.
2. Our authentication and authorisation is done via a JWT contained in the Authorization header of the request. Authentication is done via a single service that exists within the mesh, authorization is handled by each individual microservice in the mesh.
3. Our authorization policies are quite different for services within the mesh, however, each service handles it themselves.
4. Authorization is handled by each service, authentication is handled by a single service that exists within the mesh.
5. Our solution is a custom-built microservice which receives a copy of the Authorization header from the original request and returns either a 200 or 401 HTTP response. If a 200 response is returned then the request continues, otherwise the request is rejected.

**Comment by bcelenza** [comment]
Thanks for the feedback @RyanFrench! 

Can you tell me a little bit more about how you authorize a caller once you’ve authenticated them? For example, do you do authorization based on HTTP verb and path, or is it more complex than that?

Additionally, have you looked into [Open Policy Agent](https://www.openpolicyagent.org/) for both the authN and authZ functionality? I’m curious how it compares to your existing implementation.

**Comment by RyanFrench** [comment]
Once the call is authenticated we have very simple information within the JWT that points to the permissions of the caller for each resource they are allowed access to. This typically gives read/write access to a specific resource ID, and the individual service will determine if the service is allowed to read or modify the resource based on what the path does.

We haven't looked into the Open Policy Agent. It does look interesting although I think it's a little bit different in terms of the implementation. Our implementation is done in code, not via configuration.

**Comment by jlpettersson** [comment]
I would like to have two instances of my app, e.g. two different kubernetes `Deployment` and then declare JWT-rules, e.g. users with this "claim" are routed to version A and users without that JWT-claim can be routed to the other instance, version B.

In this way, I can configure what users are belonging to an early-test-group, so I can have early features in one Deployment, but only stable features in the other Deployment.

Yes, it would be good if I can use OpenPolicyAgent - but I have not understood if I an achieve this setup yet.

**Comment by bcelenza** [comment]
Hey @jlpettersson, neat idea. Open Policy Agent runs on the destination service, so routing based on a JWT claim is not something that's inherently supported. However, for your use case, here's what I think would work:

1. Create a Virtual Gateway which will be responsible for routing requests to version A and version B.
2. Integrate that Gateway with OPA. OPA will validate the JWT, and optionally append headers to the request which identify the claim(s).
3. Using a Gateway Route, route the request to the appropriate Virtual Service given the header added by OPA.

Does this sound about like what you're looking for? 

Alternatively, we're also looking into native support for JWT (#81) at a later date, which could be an alternative way to do what you're describing (likely using a Virtual Gateway again).

**Comment by rajal-amzn** [comment]
Hello,
Here is our proposal for enabling authorization of incoming traffic. We propose to use Envoy proxy's [external authorization capabilities](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#config-http-filters-ext-authz) which enables authorization integration on an AppMesh endpoint’s (Virtual Node or Virtual Gateway) listener. 

Customers can configure External Authorization using a local sidecar agent that supports [Envoy's GRPC Client API](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice). This enables customers to use [Open Policy Agent](https://www.openpolicyagent.org/) for doing Authorization or customers could bring their own. 

### API Design
```
# On a VirtualNode / Virtual Gateway    
listeners:
- portMapping:
    port: 443
    protocol: http
  # (*NEW*) (*Optional*) Specifies authorization settings for this listener.
  authorization:
    external:
     # (*NEW*) (*Required*) Specifies where to send the authZ request.
     destination:
       local:
         # (*NEW*) (*Required*) Specifies listening port of the authz service
         port: 8181

     # (*NEW*) (*Required*) Specifies external authorization API selection and settings.
     api:
       # (*NEW*) (*Required*)
       xds:
         # (*Required*) Specifies which authorization API and associated options the destination understands.
         # Valid values: V2, V3
         transportVersion: V2

     # (*NEW*) (*Optional*) Specifies timeout for the authorization decision.
     timeout:
       value: 500
       unit: ms

     # (*NEW*) (*Optional*) Specifies how to handle failed calls to the authZ service.
     failure:
       # (*NEW*) (*Optional*) Specifies whether to allow the request when the authZ service fails.
       allow: NONE
       
       # (*NEW*) (*Optional*) Specifies the action to take when a failed call occurs.
       action:
         # (*NEW*) (*Optional*) Specifies the status to return to the client if the AuthZ request fails
         # Valid values: INTERNAL_SERVER_ERROR (500), FORBIDDEN (403)
         returnStatus: INTERNAL_SERVER_ERROR
```

We'd love to hear your feedback on this proposal to see whether it fit your use cases in the comments.

**Comment by danielpops** [comment]
@rajal-amzn hello,

I have a scenario where I'm using Envoy and using the ext_authz filter to talk to an opa instance on the host. In our setup we have envoy authenticating end-users via `envoy.filters.http.jwt_authn` (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto). To propagate the `verified_jwt` payload information from the filter's `payload_in_metadata` through to the ext_authz filter, we specify [metadata_context_namespaces|https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-field-config-filter-http-ext-authz-v2-extauthz-metadata-context-namespaces] in our ext_authz config. 

Our config looks like:

```
[...]
        http_filters:
        - name: envoy.filters.http.jwt_authn
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication
            providers:
                okta:
                    payload_in_metadata: verified_jwt
                    issuer: "https://yourOktaDomain.okta.com"
                    remote_jwks:
                        cache_duration: 1800s
                        http_uri:
                            uri: https://yourOktaDomain.okta.com/oauth2/v1/keys
                            cluster: jwks_cluster
                            timeout: 60s
            rules:
              - match:
                  prefix: /
                requires:
                  requires_any:
                    requirements:
                      - provider_name: okta
                      - allow_missing_or_failed: {}
        - name: envoy.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
            failure_mode_allow: false
            grpc_service:
              envoy_grpc:
                cluster_name: opa_grpc
              timeout: 0.5s
            metadata_context_namespaces:
            - envoy.filters.http.jwt_authn
```

**Comment by dfezzie** [comment]
Hey @danielpops. In this initial iteration of external authorization support I don't believe we would support the `metadata_context_namespaces` since we do not currently support using the [JWT AuthN filter](https://github.com/aws/aws-app-mesh-roadmap/issues/81). It definitely should be considered as part of that work though.

**Comment by Gurpartap** [comment]
One of the use case is to verify external [signed http requests](https://tools.ietf.org/html/draft-cavage-http-signatures-12).

It requires comparison of the `digest` value from header with a generated value using the request body. Subsequently, this digest is used to verify the request `signature`.

Envoy's `ext_authz`, by default, does not include the request body in the CheckRequest parameter. The `with_request_body: { … }` option is required for CheckRequest parameter to include the request body.

I hope there'll be an option to enable this with app mesh's extauthz implementation.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto

```yaml
- name: envoy.filters.http.ext_authz
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
    transport_api_version: V3
    grpc_service:
      envoy_grpc:
        cluster_name: api-gateway-ext-authz
      timeout: 0.25s
    with_request_body: # 👈
      max_request_bytes: 10240  # 👈
      allow_partial_message: false  # 👈
    failure_mode_allow: false
    include_peer_certificate: true
```
