### ISSUE TITLE
Pods don't get auto registered/deregistered in kubernetes with Cloud Map

### ISSUE THREAD

**Issue by pksinghus** [aws/aws-app-mesh-roadmap#146]
**Summary**
When I scale up the deployment behind a VirtualNode in kubernetes, the additional pods don’t get registered with Cloud Map. Similarly, while scaling down the IP addresses/service instances stay registered with the service and have to be manually deregistered.

**Steps to Reproduce**
Create a Cloud Map namespace pointing to the VPC of EKS cluster
Create a mesh
Deploy any sample that works with Cloud Map as service discovery
Scale up the deployment
Additional pods/IP addresses created are not registered as service instances in Cloud Map
Scale down the deployment
Pods/IP addresses stay registered in Cloud Map

**Are you currently working around this issue?**
No.

**Additional context**

**Attachments**
[manifest.yaml.txt](https://github.com/aws/aws-app-mesh-roadmap/files/3986150/manifest.yaml.txt)
This manifest can be deployed as an example. Auto registration of pods doesn't happen. Cloud Map namespace is assumed to be `dj-cloudmap.pvt.aws.local`

**Comment by pksinghus** [comment]
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: dj-cloudmap
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
  name: dj-cloudmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj
  namespace: dj-cloudmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: dj-cloudmap
      labels:
        app: dj
        version: v1
    spec:
      containers:
        - name: dj
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "DJ Reporting for duty!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-v1
  namespace: dj-cloudmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metal
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: dj-cloudmap
      labels:
        app: metal
        version: v1
    spec:
      containers:
        - name: metal
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Megadeth\",\"Judas Priest\"]"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jazz-v1
  namespace: dj-cloudmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jazz
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: dj-cloudmap
      labels:
        app: jazz
        version: v1
    spec:
      containers:
        - name: jazz
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Astrud Gilberto\",\"Miles Davis\"]"
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: dj
  namespace: dj-cloudmap
spec:
  meshName: dj-cloudmap
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: dj-cloudmap.pvt.aws.local
      serviceName: dj
  backends:
    - virtualService:
        virtualServiceName: jazz.dj-cloudmap.pvt.aws.local
    - virtualService:
        virtualServiceName: metal.dj-cloudmap.pvt.aws.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: jazz-v1
  namespace: dj-cloudmap
spec:
  meshName: dj-cloudmap
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: dj-cloudmap.pvt.aws.local
      serviceName: jazz
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: metal-v1
  namespace: dj-cloudmap
spec:
  meshName: dj-cloudmap
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    cloudMap:
      namespaceName: dj-cloudmap.pvt.aws.local
      serviceName: metal
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: jazz.dj-cloudmap.pvt.aws.local
  namespace: dj-cloudmap
spec:
  meshName: dj-cloudmap
  virtualRouter:
    name: jazz-router
    listeners:
      - portMapping:
          port: 9080
          protocol: http
  routes:
    - name: jazz-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: jazz-v1
              weight: 100
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: metal.dj-cloudmap.pvt.aws.local
  namespace: dj-cloudmap
spec:
  meshName: dj-cloudmap
  virtualRouter:
    name: metal-router
    listeners:
      - portMapping:
          port: 9080
          protocol: http
  routes:
    - name: metal-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: metal-v1
              weight: 100

```
Sample app.
