### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol for openssl command from a different service in the same mesh

### ISSUE THREAD

**Issue by aboutbelka** [aws/aws-app-mesh-roadmap#200]
I've configured TLS on the server node using a Private certificate from PCA and set a client policy to enforce TLS on the client.

Both the server and the client nodes have the following permissions added to the policy:
        "acm:ExportCertificate",
        "acm-pca:GetCertificateAuthorityCertificate",
        "appmesh:StreamAggregatedResources",
        "acm-pca:DescribeCertificateAuthority"

When I run  openssl s_client -connect my-service-name.co.uk:443/ I get the correct response
When I run the same from a different service inside the same mesh I get:

`CONNECTED(00000003)
140065377040032:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
`
Attaching my json configs for the server and the client (applied through aws-cli on existing ECS fargate services)
[github.zip](https://github.com/aws/aws-app-mesh-examples/files/4624589/github.zip)

**Comment by aboutbelka** [comment]
Hi @bcelenza,
Thanks for coming back to me.

I tried changing the server application to http and port 80.

Without TLS - for wget command I get 404 (which is expected as nothing is listening there) from the client node
With TLS - I get 503 
Tried both with and without the client policy on the client node.
Still works fine from the bastion with http and port 80 instead of https:443
Looks like smth is wrong with the mesh?

**Comment by bcelenza** [comment]
@aboutbelka So I can reproduce this behavior, and I can walk you through why this is the case.

### Reproduction

I setup a 2-node mesh like you had with a client hosting SSH and an upstream server hosting a simple HTTP service that echos back a 200 response code. My resources look like this (in Kubernetes format, but spec should look familiar):

Client:
```
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: client
  namespace: aviary
spec:
  meshName: aviary
  backends:
    - virtualService:
        virtualServiceName: mockingbird.aviary.svc.cluster.local
  backendDefaults:
    clientPolicy:
      tls:
        validation:
          trust:
            acm:
              certificateAuthorityArns:
                - arn:aws:acm-pca:us-east-1:XXXXXXX:certificate-authority/XXXXXXX
  logging:
    accessLog:
      file:
        path: /dev/stdout
```

Server:
```
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: mockingbird-v1
  namespace: aviary
spec:
  meshName: aviary
  listeners:
    - portMapping:
        port: 80
        protocol: http
      tls:
        mode: STRICT
        certificate:
          acm:
            certificateArn: arn:aws:acm:us-east-1:XXXXXXXX:certificate/XXXXXXXX
  serviceDiscovery:
    dns:
      hostName: mockingbird.aviary.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: mockingbird.aviary.svc.cluster.local
  namespace: aviary
spec:
  meshName: aviary
  virtualRouter:
    listeners:
      - portMapping:
          port: 80
          protocol: http
  routes:
    - name: default-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: mockingbird-v1
              weight: 1
```

When I shell into my client node, and issue an HTTP request to the mockingbird service, it succeeds:
```
$ curl -v http://mockingbird.aviary.svc.cluster.local/echo
*   Trying 10.100.125.95...
* Connected to mockingbird.aviary.svc.cluster.local (10.100.125.95) port 80 (#0)
> GET /echo HTTP/1.1
> Host: mockingbird.aviary.svc.cluster.local
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Wed, 20 May 2020 21:01:01 GMT
< content-length: 0
< x-envoy-upstream-service-time: 4
< server: envoy
<
* Connection #0 to host mockingbird.aviary.svc.cluster.local left intact
```

But an HTTPS request, on the other hand:
```
$ curl -vk https://mockingbird.aviary.svc.cluster.local:80/echo
*   Trying 10.100.125.95...
* Connected to mockingbird.aviary.svc.cluster.local (10.100.125.95) port 80 (#0)
* error reading ca cert file /etc/ssl/certs/ca-certificates.crt (Error while reading file.)
* found 0 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
```

And when I verify with openssl:
```
$ openssl s_client -connect mockingbird.aviary.svc.cluster.local:80
CONNECTED(00000003)
139747333252760:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1590006493
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

### So why is this happening?

I'm going to borrow a diagram from our [TLS blog post](https://aws.amazon.com/blogs/containers/enable-traffic-encryption-between-services-in-aws-app-mesh-using-aws-certificate-manager-or-customer-provided-certificates/) to help explain this.

![TLS diagram](https://d2908q01vomqb2.cloudfront.net/fe2ef495a1152561572949784c16bf23abb28057/2020/03/13/Diagram-1-2-2-1024x699.jpg)

The current App Mesh TLS model configures the client and server proxies to negotiate TLS. So when I send the HTTP (not HTTPS) request from curl above, the communication path looks like:

```
curl ---Plain Text---> Client Envoy ---TLS---> Server Envoy ---Plain Text---> Server Application
```

This works, because the Client Envoy is configured to intercept HTTP requests on port 80, negotiate TLS upstream with the server envoy and send the traffic that way.

The HTTPS, by comparison, looks like this:

```
curl ---TLS---> Client Envoy ---XXX--> (request fails)
```

The reason the request fails is this: the Client Envoy is not expecting to negotiate TLS with the curl application. And because the curl application is attempting to negotiate TLS with the Client Envoy, it fails, because the TLS session cannot be established.

The same failure can be observed by `openssl`, because the Client Envoy is intercepting the traffic for both, and failing to negotiate TLS.

### Where to go from here?

In effect, this is the intended behavior of the current TLS implementation. If the application (curl or wget for example) wants to negotiate TLS, then the Client Envoy would either need to terminate TLS and re-negotiate with the Server Envoy, or proxy the traffic as pure TCP. The former option adds complexity in setup, and the latter means you'd lose all of the benefits of Layer 7 request routing, observability, etc.

That said, would your expectation be to have the client application originate the TLS session instead? If so, we have a roadmap item for this and I'd love to have your +1 and feedback on it: #162.


I hope this explanation of the behavior helped, and let me know what your ideal communication path looks like.
