### ISSUE TITLE
Bug: TCP Route targets with 0 weight are rejected by Envoy

### ISSUE THREAD

**Issue by landesherr** [aws/aws-app-mesh-roadmap#204]
## Description:

TCP Route targets with 0 weight are rejected by Envoy, despite being accepted by App Mesh

## Repro Steps:

Given a weighted TCP Route between two Virtual Node backends, blue and green, such as in the following spec:
```
tcpRoute:
    action:
      weightedTargets:
      - virtualNode: green
        weight: 50
      - virtualNode: blue
        weight: 50
```

Attempt to update the Weighted Targets of the route such that 100% of the traffic is routed to blue, giving green a weight of zero:

```
tcpRoute:
    action:
      weightedTargets:
      - virtualNode: green
        weight: 0
      - virtualNode: blue
        weight: 100
```

## Result:

App Mesh will accept this configuration without error. However, when the transformed configuration reaches Envoy, it results in Envoy sending a NACK for the new configuration change, logging the following error: `ClusterWeightValidationError.Weight: ["value must be greater than or equal to " '\x01'].` The previously applied configuration will remain active, and the new configuration that was just pushed will be ignored in its entirety.

It seems that App Mesh is making an incorrect assumption about valid weights in a TCP weighted route.
