### ISSUE TITLE
Question: CloudMap discovery, does it use the mesh?

### ISSUE THREAD

**Issue by benpettman** [aws/aws-app-mesh-roadmap#225]
I got a mesh running with dns discovery and everything works as expected, then using the [howto](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-cross-cluster) examples I swapped out the dns discovery for ```awsCloudMap``` discovery, after some tweaking of references I can exec into my curler pod that is part of the mesh (the one that was working when using local dns) and then made a curl out to the CloudMap url.

I get a response, but the response is just a round robin over the 2 pods that have been registered to the service, my assumption would of been this would of been routed via the envoy proxy in the curler pod, out to CloudMap and then back to the Mesh and routed me as it did when using local dns.

It seems that CloudMap gets the pods running as their endpoints and then by calling the CloudMap URL it negates the mesh entirely and just replies with each pod in turn. See curl output below:

```
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":true}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":"thisshouldbetrue"}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":true}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":"thisshouldbetrue"}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":true}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":"thisshouldbetrue"}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
{"healthStatus":true}
root@curler-574d66489f-tnf5j:/# curl api-cm3.search.travelverse.local/health
```

It should just be replying with ```{"healthStatus":true}``` unless a header is supplied

Below are my test files, both dns and cloudmap versions. Again please advise if this is wrong.

DNS:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    mesh: search-api
  name: search
  
---

apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: search-api
spec:
  namespaceSelector:
    matchLabels:
      mesh: search-api

---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v1
  namespace: search
spec:
  podSelector:
    matchLabels:
      app: api
      version: v1
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    dns:
      hostname: api-search-v1.search.svc.cluster.local

---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v2
  namespace: search
spec:
  podSelector:
    matchLabels:
      app: api
      version: v2
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    dns:
      hostname: api-search-v2.search.svc.cluster.local

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: api
  namespace: search
spec:
  awsName: api.search.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: api
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: search
  name: api
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: health-route
      priority: 11
      httpRoute:
        match:
          prefix: /health
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v1
              weight: 1
    - name: health-route-header
      priority: 10
      httpRoute:
        match:
          prefix: /health
          headers:
            - name: health_header
              match:
                exact: blue
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v2
              weight: 1
    - name: api-route
      priority: 10
      httpRoute:
        match:
          prefix: /search
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v1
              weight: 1
            - virtualNodeRef:
                name: search-v2
              weight: 1
---

apiVersion: v1
kind: Service
metadata:
  name: api-search-v1
  namespace: search
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-v1
  namespace: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: v1
  template:
    metadata:
      metadata:
      annotations:
        appmesh.k8s.aws/egressIgnoredPorts: "3306"
      labels:
        app: api
        version: v1
    spec:
      containers:
      - name: search-one
        image: xxx
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          value: slave.search.travelverse.local
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: CSlp6JwXGz
        - name: DB_NAME
          value: holidaycottages
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: gitlab-auth-token
---
apiVersion: v1
kind: Service
metadata:
  name: api-search-v2
  namespace: search
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-v2
  namespace: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: v2
  template:
    metadata:
      metadata:
      annotations:
        appmesh.k8s.aws/egressIgnoredPorts: "3306"
      labels:
        app: api
        version: v2
    spec:
      containers:
      - name: search-one
        image: xxx
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          value: slave.search.travelverse.local
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: CSlp6JwXGz
        - name: DB_NAME
          value: holidaycottages
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: gitlab-auth-token

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: search
  labels:
    app: api
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api
---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: curler
  namespace: search
spec:
  podSelector:
    matchLabels:
      app: curler
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: api
  serviceDiscovery:
    dns:
      hostname: curler.search.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: curler
  namespace: search
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: curler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curler
  namespace: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curler
  template:
    metadata:
      labels:
        app: curler
    spec:
      containers:
      - name: blue-website
        image: scrapinghub/httpbin:latest
        command:
        - sleep
        - "3600"
        resources:
          requests:
            cpu: 0.1
            memory: 200

```

CloudMap:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    mesh: search-api-cm3
  name: search-cm
  
 ---

apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: search-api-cm3
spec:
  namespaceSelector:
    matchLabels:
      mesh: search-api-cm3

---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v1
  namespace: search-cm
spec:
  podSelector:
    matchLabels:
      app: api-cm3
      version: v1
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: search.travelverse.local
      serviceName: api-cm3

---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v2
  namespace: search-cm
spec:
  podSelector:
    matchLabels:
      app: api-cm3
      version: v2
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: search.travelverse.local
      serviceName: api-cm3

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: search-cm
  name: api-cm3
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: health-route
      priority: 11
      httpRoute:
        match:
          prefix: /health
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v1
              weight: 1
    - name: health-route-header
      priority: 10
      httpRoute:
        match:
          prefix: /health
          headers:
            - name: health_header
              match:
                exact: blue
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v2
              weight: 1
    - name: api-cm3-route
      priority: 10
      httpRoute:
        match:
          prefix: /search
        action:
          weightedTargets:
            - virtualNodeRef:
                name: search-v1
              weight: 1
            - virtualNodeRef:
                name: search-v2
              weight: 1

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: api-cm3.search.travelverse.local
  namespace: search-cm
spec:
  awsName: api-cm3.search.travelverse.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: api-cm3
        namespace: search-cm
---

apiVersion: v1
kind: Service
metadata:
  name: api-cm3-search-v1
  namespace: search-cm
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api-cm3
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-v1
  namespace: search-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cm3
      version: v1
  template:
    metadata:
      metadata:
      annotations:
        appmesh.k8s.aws/egressIgnoredPorts: "3306"
      labels:
        app: api-cm3
        version: v1
    spec:
      containers:
      - name: search-one
        image: xxx
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          value: slave.search.travelverse.local
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: CSlp6JwXGz
        - name: DB_NAME
          value: holidaycottages
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: gitlab-auth-token
---
apiVersion: v1
kind: Service
metadata:
  name: api-cm3-search-v2
  namespace: search-cm
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api-cm3
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-v2
  namespace: search-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cm3
      version: v2
  template:
    metadata:
      metadata:
      annotations:
        appmesh.k8s.aws/egressIgnoredPorts: "3306"
      labels:
        app: api-cm3
        version: v2
    spec:
      containers:
      - name: search-one
        image: xxx
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          value: slave.search.travelverse.local
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: CSlp6JwXGz
        - name: DB_NAME
          value: holidaycottages
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: gitlab-auth-token

---
apiVersion: v1
kind: Service
metadata:
  name: api-cm3
  namespace: search-cm
  labels:
    app: api-cm3
spec:
  ports:
    - port: 7000
      name: http
  selector:
    app: api-cm3
---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: curler
  namespace: search-cm
spec:
  podSelector:
    matchLabels:
      app: curler
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: api-cm3.search.travelverse.local
  serviceDiscovery:
    awsCloudMap:
      namespaceName: search.travelverse.local
      serviceName: curler

---

apiVersion: v1
kind: Service
metadata:
  name: curler
  namespace: search-cm
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: curler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curler
  namespace: search-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curler
  template:
    metadata:
      labels:
        app: curler
    spec:
      containers:
      - name: blue-website
        image: scrapinghub/httpbin:latest
        command:
        - sleep
        - "3600"
        resources:
          requests:
            cpu: 0.1
            memory: 200

```

**Comment by bcelenza** [comment]
From the Cloud Map configuration you've shared, it looks like the virtual nodes `search-v1` and `search-v2` are indistinguishable from each other because they both have the exact same service discovery settings (`namespaceName: search.travelverse.local`, `serviceName: api-cm3`). So what's happening is, regardless which weighted target Envoy selects, you're likely getting a mixture of responses from each virtual node and pod associated with it.

You can distinguish between the two of them by providing a unique [Cloud Map attribute](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_AwsCloudMapInstanceAttribute.html) for each node, which should resolve this issue. For example:

```
---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v1
  namespace: search-cm
spec:
  podSelector:
    matchLabels:
      app: api-cm3
      version: v1
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: search.travelverse.local
      serviceName: api-cm3
      attributes:
        - key: version
           value: v1

---

apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: search-v2
  namespace: search-cm
spec:
  podSelector:
    matchLabels:
      app: api-cm3
      version: v2
  listeners:
    - portMapping:
        port: 7000
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: search.travelverse.local
      serviceName: api-cm3
      attributes:
        - key: version
           value: v2
```
