### ISSUE TITLE
Cannot Access AWS RDS from App Mesh

### ISSUE THREAD

**Issue by nitinkapur** [aws/aws-app-mesh-roadmap#270]
We have a AWS EKS Fargate cluster with a service that connects to RDS DB and ElasticCache on AWS. I have setup a mesh with Egress traffic allowed and deployed  a virtual node and virtual service.

```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: ganesh-permissions
  namespace: dev
spec:
  awsName: ganesh-permissions.dev.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: ganesh-permissions-vnode
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: ganesh-permissions-vnode
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: ganesh-permissions
  listeners:
    - portMapping:
        port: 80
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: ganesh-permissions
  serviceDiscovery:
    dns:
      hostname: ganesh-permissions.dev.svc.cluster.local
```

I can now access the service api through load balancer and there is a version number call that I can make which returns the version number and a 200 trace is available in X-Ray. After this there is a call that I make to get some data from the service which uses an authentication header to authenticate the user and then should pull the data and return results. But this call fails and I do see a 504 error logged in the X-Ray traces. 

Now either the service is not accepting headers or it is having issue with connecting to the database. How to make sure it can connect to the DB? The pod uses a connection string to connect to the AWS RDS MS SQL Server

![image](https://user-images.githubusercontent.com/10778343/95161641-b851ce80-0771-11eb-9ae8-7d3344f310a6.png)
