### ISSUE TITLE
Feature Request: Add IAM Managed Policy for aws-appmesh-envoy ECR Access

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-app-mesh-roadmap#304]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

I would prefer the use of a managed policy for adding access to ECR repositories. This would have the benefit of more consistent integration across all AWS customers (fewer issues) as well as future-proofing if additional access is needed in the future.

**Which integration(s) is this request for?**

This requested addition is for all organizations that use IAM roles in order to access repositories where IAM roles are used to access the `aws-appmesh-envoy` image.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The existing implementation looks like:

```
      Policies:
        - PolicyName: aws-appmesh-envoy-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: !Sub arn:aws:ecr:${AWS::Region}:840364872350:repository/aws-appmesh-envoy
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
```

But the desired implementation would look like this:

```
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAppMeshECRAccessPolicy
```

or

```
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAppMeshECRAccessPolicy
```

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**

This creates a situation where Engineering effort is spent managing permissions across multiple customers as opposed to centrally by a trusted authority (AWS). It's highly likely that the aggregate of customers have made far more errors managing this bit of code than AWS would. This would help create a "finished" look for the AppMesh product as well (i.e. official integration with IAM).

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
