### ISSUE TITLE
Feature Request: Support Server Name Indication (SNI)

### ISSUE THREAD

**Issue by bigdefect** [aws/aws-app-mesh-roadmap#311]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
App Mesh can enable configuration of SNI on backends in Virtual Node to allow TLS connections in situations where an endpoint serves multiple certificates.
Similarly, for Virtual Gateways, App Mesh needs to support vending different certificates based on the SNI where the Virtual Gateway serves different hosts.

**Which integration(s) is this request for?**
All platforms.

**Tell us about the problem you're trying to solve.**
Currently, App Mesh doesn't configure SNI for Virtual Node backends, so negotiating TLS with either external endpoints, or TLS-terminating applications, which vend multiple certificates based on SNI, is not possible unless the default certificate is the desired one.

Similarly, for Virtual Gateway, App Mesh doesnt allow vending certificates depending on the SNI headers in the request. It only allows a default certificates right now.

**Are you currently working around this issue?**
No current workarounds.

**Comment by efe-selcuk** [comment]
Question to those with interest in this feature, would you need the SNI to be configurable? Or if we configured it by default using a convention, would that be enough?

For example, today we configure the expected SAN to match the service discovery settings on the peer virtual node. We could, for example, default the SNI to the virtual service name or the service discovery name.

**Comment by mmf55** [comment]
I think an approach like you currently have for the SAN fits most of the use cases. But having default and the capability of changing it to a different value would also be handy for some specific use cases.
Default the SNI to the service discovery name seems to be the best approach in my opinion.

**Comment by mkielar** [comment]
> today we configure the expected SAN to match the service discovery settings

@bigdefect can you elaborate on how this is configured? I'm currently trying to map an 3rd party service which is hosted behind AWS API Gateway + Cloudfront, so that AppMesh Services should connect to it via HTTP, and Envoy would initiate TLS, and I'm failing to do so because of the dreaded:
```
TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

I've set up local envoy (not the appmesh one) with some simple configuration, and when I added the `sni:` parameter it all started to work. Then I dumped the configuration of my AppMesh Envoy running on ECS Fargate to see how the upstream configuration looks there, and I see no `sni:` configured there. So what can I do to make this right?

This works on my local envoy:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service-https
                  host_rewrite_literal: api.dev-atech.com
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: service-https
    type: STRICT_DNS
    connect_timeout: 15s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service-https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: [MASKED] ### Points to Public API Gateway
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: [MASKED] ### Points to Public API Gateway
        common_tls_context:
          validation_context:
            match_subject_alt_names:
            - exact: [MASKED] ### Points to Public API Gateway
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
```
Note: All the `[MASKED]` values are the same and point to a real domain, jus cannot disclose it because of NDA.

This is related fragment of the AppMesh Envoy configuration:
```
{
     "version_info": "1434024066:-2086145894:63fde0ef00cdd14ba82c8a1e1599341e0525354f",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "cds_egress_dev_[MASKED]_http_443",
      "type": "LOGICAL_DNS",
      "connect_timeout": "1s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 2147483647,
         "max_pending_requests": 2147483647,
         "max_requests": 2147483647,
         "max_retries": 2147483647
        }
       ]
      },
      "transport_socket": {
       "name": "envoy.transport_sockets.tls",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
        "common_tls_context": {
         "validation_context": {
          "trusted_ca": {
           "filename": "/etc/ssl/certs/ca-bundle.crt"
          },
          "match_subject_alt_names": [
           {
            "exact": "[MASKED]" ### The same API Gateway Hostname
           }
          ]
         }
        }
       }
      },
      "metadata": {
       "filter_metadata": {
        "aws.appmesh.aggregate_stats": {
         "config": "{\"tags\":[{\"key\":\"TargetVirtualNode\",\"value\":\"[MASKED]\"}]}"
        }
       }
      },
      "load_assignment": {
       "cluster_name": "cds_egress_dev_[MASKED]_http_443",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "[MASKED]", ### The same API Gateway Hostname
              "port_value": 443
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2021-10-29T17:27:02.555Z"
    },
```

Tested with Envoy 1.19.0 and AppMesh Envoy `v1.19.1.0-prod`.
I tested this with two different Public API Gateways, one with mTLS, and one with TLS. Neither worked.
I also tested identical configuration (HTTP from the app, then TLS initiated on Envoy) with `api.stripe.com` and confirm envoy properly initiates TLS for me.

This looks bad because it looks like AppMesh Envoy is unable to wrap API Gateway / Cloudfront as external AppMesh Services with HTTP.
