### ISSUE TITLE
Feature Request: Inject the virtual gateway's original host header

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-app-mesh-roadmap#322]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
I'd like for a Virtual Gateway to add the originally-requested HTTP host header into HTTP & HTTP/2 requests it sends to the mesh.

**Which integration(s) is this request for?**
I'm using the AppMesh envoy container image on Fargate/ECS, but I think this request is more about configuration management for gateway routes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My services want to know what HTTP host was used when the user's request was sent to the gateway. These services want to use the hostname to create absolute URLs dynamically, based on whichever host was sent to the gateway. However, the original host header is overwritten with the name of my service before my services receive the request. Because this information is not available when a request arrives at my service, my use case may be impossible if AppMesh's Virtual Gateway-configured envoy receives the request first.

**Are you currently working around this issue?**
Yes, but I'm not happy with how I needed to do it. I put another envoy with a static config in front of the Virtual Gateway envoy to add `X-Forwarded-Host` before AppMesh gets involved. My statically configured envoy relays traffic to the AppMesh Virtual Gateway listener on a second container on my Fargate tasks. Here's my static envoy config:

```yaml
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          # [1] The load balancer hits this listener.
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.filters.http.router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: appmesh_envoy
                          request_headers_to_add:
                            # [2] Add an X-Forwarded-Host from the request's current host name.
                            - header:
                                key: "X-Forwarded-Host"
                                value: "%REQ(Host)%"
                              append: true
  clusters:
    - name: appmesh_envoy
      connect_timeout: 1s
      type: STATIC
      load_assignment:
        cluster_name: appmesh_envoy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      # [3] Send the request to the AppMesh gateway on its listener
                      address: 127.0.0.1
                      port_value: 8081
      transport_socket:
        name: envoy.transport_sockets.raw_buffer
```

**Additional context**
Here's an example of a request that `jmalloc/echo-server` received from a virtual gateway before I added my workaround:

```
Request served by ip-10-0-252-150.ca-central-1.compute.internal

HTTP/2.0 GET /

Host: echo.integ-environment
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Accept-Encoding: gzip, deflate
X-Envoy-Original-Path: /
X-Envoy-Expected-Rq-Timeout-Ms: 15000
X-Forwarded-For: <removed>
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Language: en-US,en;q=0.9
X-Request-Id: 6fe7d1bf-e994-9c4e-8e72-a7bc9a1ce7c1
X-Forwarded-Proto: http
X-Forwarded-Port: 80
X-Amzn-Trace-Id: Root=1-603a7f2d-51aebabc5b128e3b36dafc9e
```

Envoy allows you to add the host header to routes this way:

```
request_headers_to_add:
  - header:
      key: "X-Forwarded-Host"
      value: "%REQ(Host)%"
    append: true
```
