### ISSUE TITLE
Feature Request: gRPC <-> JSON Transcoder Filter

### ISSUE THREAD

**Issue by Gurpartap** [aws/aws-app-mesh-roadmap#340]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

With an API service built using gRPC, it would be useful if the sidecar proxy could transcode Protobuf <-> JSON for API clients that aren't aware of gRPC or Protobuf.

Envoy already comes with the `envoy.filters.http.grpc_json_transcoder` filter, which could be adopted for implementing this feature.

```yaml
- name: envoy.filters.http.grpc_json_transcoder
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
    proto_descriptor: "path/to/proto/my-api/descriptor.pb"
    # proto_descriptor_bin: # (cat path/to/proto/my-api/descriptor.pb | base64)
    services: [
        "myproj.myapi.v0.APIService",
        "myproj.myapi.v0.HealthService"
    ]
    print_options:
      add_whitespace: true
      always_print_primitive_fields: true
      always_print_enums_as_ints: false
      preserve_proto_field_names: false
```

Any time the service proto changes, it would require that the `proto_descriptor` is updated, and the envoy proxy is told to reapply the filter.

I'm currently using `grpc-gateway` to implement the same. It requires the use of Go.
