### ISSUE TITLE
Feature Request: more flexibile listener options

### ISSUE THREAD

**Issue by Rob-Johnson** [aws/aws-app-mesh-roadmap#346]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Currently, App Mesh has a strict requirement that a user must connect to Virtual Services by making a call with the `Host` header set to the name of the target virtual service. All requests currently reach the same listening port in the App-Mesh managed Envoy.

We'd like more flexible options for the listener that's set in Envoy. In our current mesh, we support:

- Routing to a specific port that's assigned to a service
```
- "@type": type.googleapis.com/envoy.api.v2.Listener
  name: cockroachdb.main.egress_listener.proxy_port
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 20707
  reuse_port: True
  filter_chains:
  - filters:
    - name: envoy.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
        stat_prefix: egress_tcp
        cluster: cockroachdb.main.egress_cluster
        idle_timeout: 600s
        max_connect_attempts: 2
```

- Routing via a unix socket
```
- "@type": type.googleapis.com/envoy.api.v2.Listener
  name: service.default.svc.cluster.local.unix_socket
  address:
    pipe:
      path: /var/run/envoy/sockets/service.default.svc.cluster.local.sock
      mode: 438
  filter_chains:
  - filters:
    - name: envoy.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
        stat_prefix: egress_tcp
        cluster: service.default.svc.cluster.local
```

- Routing based on the name of a specific header. We currently use a very simple filter that implements this for us.

**Which integration(s) is this request for?**
We use app mesh with Kubernetes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
There are a few motivations here:
- Our current service mesh supports more flexible listener options than app mesh currently supports, making our migration significantly more difficult than it might otherwise be.
- The services that we run currently *may* depend on the value of the `Host` header matching that which was first set by the client (`www.foo.com`). Though we understand this isn't strictly 'correct', we'd like the flexibility to be able to maintain this guarantee at the infrastructure tier, rather than asking users to understand the details of how the minutiae of routing/listening details change in our mesh over time.
- Unix sockets are more performant than using the tcp stack to reach something that is running on the same host; we use this for those services where we want to improve performance most.

**Are you currently working around this issue?**
To solve this right now, we're thinking of running a *second* envoy proxy which sits between the client and the app-mesh envoy to paper over the missing features.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
