### ISSUE TITLE
Feature Request:Please pass x-forward-client-cert details through listener for introspection

### ISSUE THREAD

**Issue by caleygoff-invitae** [aws/aws-app-mesh-roadmap#356]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Would it be possible to pass the XFCC (`x-forwarded-client-cert`) headers through the listener to the workloads behind the envoy sidecars?

Would that be an easier ask to allow for request auditing of requests by the community in the meantime while we wait for listener `filter_chain` to be extended to allow for `ext_authz`?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
While we wait for Appmesh to officially support ext_authz and enable x509 validation by performing introspection on the request in the dynamic listener filter chain with OPA and the spiffeID of an authorised workload. We can create a static_listener and its own filter_chain and append that to the envoy.yaml created by the `envoy-bootstrap` when the sidecar turns on. This requires some customization on the `envoy-wrapper` but nothing to terrible. 

However when doing this, it is apparent that Appmesh is not forwarding the `x-forwarded-client-cert` details through the listener   which makes any filter_chain behind the listener and maybe an OPA sidecar unable to properly authorize a request. This is conjecture on my part, but it seems like with the mTLS validation enabled on the appmesh listeners, there is some sort of TLS introspection happening. If the XFCC headers are being made available to the listeners, is it possible those also be made available to the workloads behind the listeners too? 

**Are you currently working around this issue?**
I'm unable to actually perform auditing on requests that are protected at the appmesh listener. We can "trust" that the listeners are only accepting the requests from a listener in the SAN list with mTLS but OPA behind the listener isn't able to also perform validation. 

**Additional context**
I am appending a static listener for a workload that is sending requests out of the container to the mesh by appending the chain which listens on `127.0.0.1:XXXX` where XXXX is the VirtualNode port that is attached to this workload and sends the request to be audited by OPA before routing it back to the listener on `rds_ingress_http_XXXX` where `XXXX` is the VirtualNode port that is attached to this workload. This listener is discovered by the `adsConfig` which points to the Appmesh `aDS` data-plane. So this will perform service discovery that matches the host in the request. 

Note that I have set the `forward_client_cert_details` on the listener below and even if I add a `tls_context` to this listener its unable work.
```
frontend
# it is helpful to run yamllint on this file.
---
staticResources:
  listeners:
    - name: outbound_proxy
      address:
        socket_address:
          address: 127.0.0.1
          port_value:  9001
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                common_http_protocol_options:
                  idle_timeout: 1s
                forward_client_cert_details: SANITIZE_SET   👈 
                set_current_client_cert_details:            👈 
                  uri: true                                 👈 
                codec_type: auto
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/tmp/outbound-proxy.log"
                stat_prefix: ingress_http
                rds:
                  route_config_name: rds_ingress_http_9001
                  config_source:
                    ads: {}
                http_filters:
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                      with_request_body:
                        max_request_bytes: 8192
                        allow_partial_message: true
                      failure_mode_allow: false
                      grpc_service:
                        google_grpc:
                          target_uri: 127.0.0.1:8182
                          stat_prefix: ext_authz
                        timeout: 0.5s
                  - name: envoy.router
```

I am appending a static listener for a workload that is receiving requests from outside of the container fromt the mesh by appending the chain which listens on `0.0.0.0:XXXX` where XXXX is the VirtualNode port that is attached to this workload and sends the request to be audited by OPA before routing it back a `cluster` called `local_service` on `127.0.0.1:XXXX` where `XXXX` is the port the workload listens on which the VirtualNode would attach to normally. Note that I have set the `forward_client_cert_details` on the listener below and even if I add a `tls_context` to this listener its unable work.

```
# it is helpful to run yamllint on this file.
---
staticResources:
  listeners:
    - name: local_service
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9001
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                common_http_protocol_options:
                  idle_timeout: 1s
                forward_client_cert_details: SANITIZE_SET   👈 
                set_current_client_cert_details:            👈 
                  uri: true                                 👈 
                codec_type: auto
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/tmp/inbound-proxy.log"
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_service
                http_filters:
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                      with_request_body:
                        max_request_bytes: 8192
                        allow_partial_message: true
                      failure_mode_allow: false
                      grpc_service:
                        google_grpc:
                          target_uri: 127.0.0.1:8182
                          stat_prefix: ext_authz
                        timeout: 0.5s
                  - name: envoy.router
  clusters:
    - connectTimeout: 1s
      name: local_service
      type: logical_dns
      hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 3000
```

**Attachments**

I would expect to something like 
```
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 1s
          forward_client_cert_details: sanitize_set 👈 
          set_current_client_cert_details:          👈 
              uri: true                             👈 
```

on the dynamic_listeners below for both the `rds_ingress_http_9001` and `rds_egress_http_9001` but if viewed below, the `config_dump` from the envoy sidecar doesn't show this information on the dynamic listener. 

```
# rds_ingress_http_9001
    dynamic_listeners:
      - name: lds_ingress_0.0.0.0_15000
        active_state:
          version_info: "1817419614"
          listener:
            '@type': type.googleapis.com/envoy.api.v2.Listener
            name: lds_ingress_0.0.0.0_15000
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 15000
            filter_chains:
              - filter_chain_match:
                  destination_port: 9001
                filters:
                  - name: envoy.http_connection_manager
                    config:
                      tracing: {}
                      upgrade_configs:
                        - enabled: true
                          upgrade_type: websocket
                      http_filters:
                        - name: envoy.router
                      stat_prefix: ingress
                      rds:
                        route_config_name: rds_ingress_http_9001
                        config_source:
                          ads: {}
            listener_filters:
              - name: envoy.listener.original_dst
          last_updated: "2021-06-07T20:27:05.568Z"
      - name: lds_egress_0.0.0.0_15001
        active_state:
          version_info: "1817419614"
          listener:
            '@type': type.googleapis.com/envoy.api.v2.Listener
            name: lds_egress_0.0.0.0_15001
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 15001
            filter_chains:
              - filter_chain_match:
                  prefix_ranges:
                    - address_prefix: 0.0.0.0
                      prefix_len: 0
                  destination_port: 9001
                filters:
                  - name: envoy.http_connection_manager
                    config:
                      http_filters:
                        - name: envoy.router
                      stat_prefix: egress
                      rds:
                        route_config_name: rds_egress_http_9001
                        config_source:
                          ads: {}
                      tracing:
                        operation_name: EGRESS
                      upgrade_configs:
                        - enabled: true
                          upgrade_type: websocket
              - filter_chain_match:
                  prefix_ranges:
                    - address_prefix: 0.0.0.0
                      prefix_len: 0
                  destination_port: 443
                  server_names:
                    - '*.amazonaws.com'
                filters:
                  - name: envoy.tcp_proxy
                    config:
                      stat_prefix: egress
                      cluster: cds_egress_somecorp-dev_amazonaws
              - filter_chain_match:
                  prefix_ranges:
                    - address_prefix: 0.0.0.0
                      prefix_len: 0
                filters:
                  - name: envoy.tcp_proxy
                    config:
                      stat_prefix: egress
                      cluster: cds_egress_somecorp-dev_mesh-allow-all
              - filter_chain_match:
                  prefix_ranges:
                    - address_prefix: 0.0.0.0
                      prefix_len: 0
                  destination_port: 443
                filters:
                  - name: envoy.tcp_proxy
                    config:
                      stat_prefix: egress
                      cluster: cds_egress_somecorp-dev_mesh-allow-all
            listener_filters:
              - name: envoy.listener.original_dst
              - name: envoy.listener.tls_inspector
                filter_disabled:
                  not_match:
                    or_match:
                      rules:
                        - destination_port_range:
                            start: 443
                            end: 444
                        - destination_port_range:
                            start: 9001
                            end: 9002
          last_updated: "2021-06-07T20:27:05.576Z
```

Thanks in advance
