### ISSUE TITLE
[Bug]: Gateway Route with Regex Path Match fails with Internal Failure in CloudFormation

### ISSUE THREAD

**Issue by rishijatia** [aws/aws-app-mesh-roadmap#361]
**Summary**

When trying to create a [Gateway Route](https://docs.aws.amazon.com/app-mesh/latest/userguide/gateway-routes.html) through CloudFormation that has a Regex Path Match specified, the CloudFormation Stack fails with an `Internal Failure`. 

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?

Create a valid Gateway Route in CloudFormation with spec:

```
FailingHttpGatewayRoute:
   Type: AWS::AppMesh::GatewayRoute
    Properties:
        MeshName: "your-existing-mesh"
        VirtualGatewayName: "your-existing-color-gateway"
        Spec: 
           HttpRoute:
             Match:
               Path:
                 Regex: "some-regex"
```

**Are you currently working around this issue?**

The failing Gateway Routes can be created through the AWS Console or through the AWS CLI.
