### ISSUE TITLE
Connecting to an external HTTPS endpoint

### ISSUE THREAD

**Issue by deepthawtz** [aws/aws-app-mesh-roadmap#417]
Sorry if this is redundant but I've read the all the GH Issues in this repo but have yet to see any definitive instructions to get this working. Nothing in walkthrough/examples or AWS docs on this yet but there really should be since this is a common real world use-case. If I'm wrong please point that out to me.

After two days of trying to connect a service running in App Mesh to _any_ external HTTPS API, the closest I've gotten is

```
SSL routines:ssl3_get_record:wrong version number
```

I've tried different external APIs w/ both vTLS1.2 and vTLS1.3, same thing. I theorized maybe Envoy's default `tls_minimum_protocol_version` which defaults to 1.2 was the issue but doesn't seem so.

**Comment by deepthawtz** [comment]
Example:

```
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: dog-api-node
  namespace: ${APP_NAMESPACE}
spec:
  awsName: dog-api-node
  listeners:
    - portMapping:
        port: 443
        protocol: http
  serviceDiscovery:
    dns:
      hostname: "dog.ceo"
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: "dog.ceo"
  namespace: ${APP_NAMESPACE}
spec:
  awsName: "dog.ceo"
  provider:
    virtualNode:
      virtualNodeRef:
        name: dog-api-node
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: front
  namespace: ${APP_NAMESPACE}
spec:
  podSelector:
    matchLabels:
      app: front
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: ${CLOUDMAP_NAMESPACE}
      serviceName: front
  backends:
    - virtualService:
        virtualServiceRef:
          name: "dog.ceo"
        clientPolicy:
          tls:
            validation:
              trust:
                file:
                  certificateChain: "/etc/pki/tls/cert.pem"
```

**Comment by deepthawtz** [comment]
I was reading how Istio does this (similar to App Mesh but different CRDs and implementation) https://istio.io/latest/blog/2018/egress-https/#tls-origination-by-istio 

specifically ```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rewrite-port-for-googleapis
spec:
  hosts:
  - www.googleapis.com
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: www.googleapis.com
        port:
          number: 443
```

so basically downstream app -> envoy sidecar is not encrypted and then Envoy handles the TLS negotiation w/o app knowing/caring.

**Comment by deepthawtz** [comment]
Is the way to do this via a `VirtualRouter` that listens on a port other than 443 like:

```yaml
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: ${APP_NAMESPACE}
  name: dog-api-router
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: dog-api-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: dog-api-node
              weight: 1
```
