### ISSUE TITLE
Failed to Connect to External Host via HTTPS if Multiple Backends are Defined

### ISSUE THREAD

**Issue by leo-yung** [aws/aws-app-mesh-roadmap#435]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
I can successfully connect to External Host via HTTPS if I only define one backends in the VirtualNode. But, when I added one more backends, then I will not be able connect to External Host via HTTPS anymore. 

**Steps to Reproduce**
1. Create Virtual Nodes and Virtual Services for external hosts

https://api.ipify.org
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: ipify
  namespace: poc
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
    - portMapping:
        port: 443
        protocol: tcp   
  serviceDiscovery:
    dns:
      hostname: api.ipify.org

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: api.ipify.org
  namespace: poc
spec:
  awsName: api.ipify.org
  provider:
    virtualNode:
      virtualNodeRef:
        name: ipify
```

https://www.nike.com
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: nike
  namespace: poc
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
    - portMapping:
        port: 443
        protocol: tcp   
  serviceDiscovery:
    dns:
      hostname: www.nike.com

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: www.nike.com
  namespace: poc
spec:
  awsName: www.nike.com
  provider:
    virtualNode:
      virtualNodeRef:
        name: nike

```
2. Create the Virtual Node of my service. Define single backend in the Virtual Node
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: my-service-a
  namespace: poc
spec:
  podSelector:
    matchLabels:
      app: my-service-a
  listeners:
   - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: my-service-a.poc.svc.cluster.local
  backends:
  - virtualService:
      virtualServiceRef:
        name: api.ipify.org

```

3. Create the Deployment of my service
```
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-a
  namespace: poc
  labels:
    app: my-service-a
spec:
  selector:
    app: my-service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-a
  namespace: poc
  labels:
    app: my-service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service-a
  template:
    metadata:
      labels:
        app: my-service-a
    spec:
      serviceAccountName: apps-ac 
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
```
4. Try to connect the external host api.ipify.org via the nginx container. Got successful response status 200
<img width="821" alt="image" src="https://user-images.githubusercontent.com/109689530/195866042-92a0dfc1-fb69-4d79-a80c-d2141dcd7166.png">

5. Update the Virtual Node of my service to use Nike backend
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: my-service-a
  namespace: poc
spec:
  podSelector:
    matchLabels:
      app: my-service-a
  listeners:
   - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: my-service-a.poc.svc.cluster.local
  backends:
  - virtualService:
      virtualServiceRef:
        name: www.nike.com
```
6. Try to connect the external host www.nike.com via the nginx container. Again, got successful response status 200
<img width="821" alt="image" src="https://user-images.githubusercontent.com/109689530/195865878-89648339-defb-4f5e-ab87-2d7279b7807b.png">

7. Update Virtual Node of my service with two backends
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: my-service-a
  namespace: poc
spec:
  podSelector:
    matchLabels:
      app: my-service-a
  listeners:
   - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: my-service-a.poc.svc.cluster.local
  backends:
  - virtualService:
      virtualServiceRef:
        name: www.nike.com
  - virtualService:
      virtualServiceRef:
        name: api.ipify.org
```

8. Try to connect the external host www.nike.com or api.ipify.org via the nginx container

Both result are failed...
<img width="821" alt="image" src="https://user-images.githubusercontent.com/109689530/195866721-91c9e2a7-3861-4a9f-aea9-98168220e359.png">

**Are you currently working around this issue?**
No workaround 

**Additional context**
I am using AppMesh in EKS with Fargate profile. The egress filter setting is "Deny external traffic"

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
