### ISSUE TITLE
Feature Request: Support for EKS Pod Indentities

### ISSUE THREAD

**Issue by ricardo8990** [aws/aws-app-mesh-roadmap#493]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
I think [EKS Pod Identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) are not supported at this time for the Envoy containers injected in EKS.

**Which integration(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I created an app in my EKS cluster and gave permissions using EKS Pod Identities. I'm deploying a Node App with an AppConfig container. It works fine and the permissions are working as expected. However, when I added the AppMesh integration with the Container Injected automatically I receive the following error:

```
[2024-06-26 16:00:34.205][21][error][aws] [source/extensions/common/aws/credentials_provider_impl.cc:302] Could not load AWS credentials document from the task role
[2024-06-26 16:00:34.208][15][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:152] StreamAggregatedResources gRPC config stream to appmesh-envoy-management.us-west-2.amazonaws.com:443 closed: 16, Missing Authentication Token
```

Which causes the AppConfig container to fail trying to fetch the parameters
```
appconfig agent] 2024/06/26 15:37:10 INFO AppConfig Agent 2.0.3896
[appconfig agent] 2024/06/26 15:37:10 INFO serving on localhost:2772
[appconfig agent] 2024/06/26 15:37:32 ERROR retrieve failure for 'APP:ENV:DEP': bad gateway: network error connecting to service (retry in 60s)
```

However, I can see that the env variables in the Envoy container that EKS pod identities inject into containers are correctly set:
```
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
          value: 'http://169.254.170.23/v1/credentials'
        - name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
          value: >-
            /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
```

This is the whole manifest for this particular container:
```
    - env:
        - name: APPMESH_PLATFORM_K8S_VERSION
          value: v1.29.4-eks-036c24b
        - name: APPNET_AGENT_ADMIN_UDS_PATH
          value: /tmp/agent.sock
        - name: APPMESH_PLATFORM_APP_MESH_CONTROLLER_VERSION
          value: v1.12.7-dirty
        - name: APPMESH_RESOURCE_ARN
          value: mesh/MESH/virtualNode/NODE_MESH
        - name: ENVOY_ADMIN_ACCESS_ENABLE_IPV6
          value: 'false'
        - name: APPMESH_FIPS_ENDPOINT
          value: '0'
        - name: ENVOY_LOG_LEVEL
          value: info
        - name: APPMESH_DUALSTACK_ENDPOINT
          value: '0'
        - name: APPMESH_PREVIEW
          value: '0'
        - name: ENVOY_ADMIN_ACCESS_LOG_FILE
          value: /tmp/envoy_admin_access.log
        - name: APPNET_AGENT_ADMIN_MODE
          value: uds
        - name: APPMESH_VIRTUAL_NODE_NAME
          value: mesh/MESH/virtualNode/NODE_MESH
        - name: AWS_REGION
          value: us-west-2
        - name: ENVOY_ADMIN_ACCESS_PORT
          value: '9901'
        - name: APPMESH_PLATFORM_K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
          value: 'http://169.254.170.23/v1/credentials'
        - name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
          value: >-
            /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
      image: >-
        840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.27.2.0-prod
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
              - sh
              - '-c'
              - sleep 20
      name: envoy
      ports:
        - containerPort: 9901
          name: stats
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - sh
            - '-c'
            - >-
              curl -s http://localhost:9901/server_info | grep state | grep -q
              LIVE
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
      securityContext:
        runAsUser: 1337
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount
          name: eks-pod-identity-token
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-8nkjm
          readOnly: true
```

I wonder if EKS Pod Identities are not supported at this time or if there is something I can't see.

By the way, the App Role already has permissions for `appmesh:StreamAggregatedResources` with the resource set to the Virtual Node ARN
