### ISSUE TITLE
Liveliness/readiness probes not working 

### ISSUE THREAD

**Issue by rverma-nikiai** [aws/aws-app-mesh-roadmap#58]
Describe the bug
While using the app mesh if a pod have liveliness/readiness probes it failed since the probes are configured on pod IP. 

Platform
EKS

To Reproduce
Create a pod with liveliness and readiness probe enabled.
Deploy appmesh-inject and appmesh-system
Recreate pod to observe health check failed and the pod doesn't come up

Expected behavior
A way to use liveliness/readiness probe

Additional context
A bonus would be appmesh controller can configure health check on virtual nodes automatically by reading the deployment definition.

**Comment by bcelenza** [comment]
Hey @rverma-nikiai , this looks related to https://github.com/aws/aws-app-mesh-inject/issues/32. If that looks right to you I'd like to get more information on that ticket, and close this. Does that make sense?

**Comment by rverma-nikiai** [comment]
@bcelenza I actually can't correlate both the tickets. That seems an envoy readiness issue while I raised this to highlight service containers liveliness+readiness. I am assuming that k8 scheduler tries to call the pod-ip/health-endpoint and this fails. This effects the services which have liveliness/readiness probe configured already.

**Comment by kiranmeduri** [comment]
@rverma-nikiai can you provide a sample deployment spec that shows the liveness and readiness probe settings you are using. 

I tried with following but unable to reproduce. Correct me if I am doing something wrong.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: ${APP_NAMESPACE}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: ${MESH_NAME}
      labels:
        app: front
    spec:
      containers:
        - name: app
          image: ${FRONT_APP_IMAGE}
          ports:
            - name: app-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: app-port
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: app-port
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 1
          env:
            - name: "COLOR_HOST"
              value: "color.${APP_NAMESPACE}.svc.cluster.local:8080"
```



> A bonus would be appmesh controller can configure health check on virtual nodes automatically by reading the deployment definition.

This is a good idea. I believe livenessProbe is the right setting to pick when defining health-check.
