### ISSUE TITLE
Support for extra config in Envoy at the AppMesh injector level

### ISSUE THREAD

**Issue by CharlyF** [aws/aws-app-mesh-roadmap#69]
**Tell us about your request**

👋 In order to add configurations to envoy to enable tracing or add static_resources one can use the `ENVOY_STATS_CONFIG_FILE
` environment variable. 

**Which integration(s) is this request for?**
I think this pertains to every platform supported by AppMesh ?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In my use case I want to be able to reference the VN/VS to be used for my traces, as such I need to add something like: 
```
    tracing:
      http:
        name: envoy.tracers.datadog
        config:
          collector_cluster: datadog_agent
          service_name: envoy
    static_resources:
      clusters:
      - name: datadog_agent
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: dd-agent.default.svc.cluster.local
            port_value: 8126
```
To the envoy config.

To do that, I have added the ability to pass in the env var to the envoy container and I just mount a configmap with the extra config as a volume of my application pod and as a volumeMount to the envoy container.
So that you end up with an injector manifest that contains:
```
            - name: ENVOY_STATS_CONFIG_FILE
              value: /tmp/envoy/envoyconf.yaml
```
As a result of the patch, the envoy manifest will have:
```
          volumeMounts:
            - mountPath: /tmp/envoy/
              name: dd-envoy
```
And you would need to mount the following in your apps
```
      volumes:
        - configMap:
            name: trace-cm
          name: dd-envoy   
```

As it is, people can't add extra config to envoy, I do think this would be very valuable.
The end result is:
```
Did not find Envoy configuration file at /tmp/envoy.yaml, creating one.
/tmp/envoy/envoyconf.yaml is defined, skipping generating stats_tags config
Appending /tmp/envoy/envoyconf.yaml to /tmp/envoy.yaml
Starting Envoy.
```

**Are you currently working around this issue?**

I did solve the problem by patching the injector, this is the patch [here](https://gist.github.com/CharlyF/e14832e0dbddbd544f41e61257f70cd7). I would be happy to make it cleaner, I simply something that would work asap. Let me know if you would like me to contribute upstream.

**Comment by joshuabaird** [comment]
@CharlyF How did you get around the requirement to modify the Envoy listener per the Datadog documentation [1]?

Example:

```
 listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          # Enable tracing for this listener
          tracing:
            operation_name: egress
```

Since the listener is provided dynamically by ADS, I don't think it's possible to define this statically.

[1] https://docs.datadoghq.com/tracing/setup/envoy/

**Comment by CharlyF** [comment]
I had to patch the Appmesh injector to support the extra config file so I could register the listener, as I explain in the initial note.
The patch can be found [here](https://gist.github.com/CharlyF/e14832e0dbddbd544f41e61257f70cd7)
This will allow you to add the listener as described in the doc.

Let me know if I am missing something.
Best,
.C

**Comment by joshuabaird** [comment]
@CharlyF I'm not seeing anything in your patch regarding the listener configuration - only the `cluster` and `tracing` config.  But.. maybe I'm missing something?!

**Comment by CharlyF** [comment]
I don't recall setting those up,  but it's been a while since I last did it.
I connected to my cluster and this is the conf used by one of my envoys

```
bash-4.2$ cat tmp/envoy.yaml
admin:
  access_log_path: /tmp/envoy_admin_access.log
  # Provides access to: http://<envoy hostname>:9901/config_dump
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
node:
    id: mesh/dj-app/virtualNode/dj-prod
    cluster: mesh/dj-app/virtualNode/dj-prod
dynamic_resources:
  # Configure Envoy to get listeners and clusters via GRPC ADS
  ads_config:
    api_type: GRPC
    grpc_services:
      google_grpc:
        target_uri: appmesh-envoy-management.us-east-1.amazonaws.com:443
        stat_prefix: ads
        channel_credentials:
          ssl_credentials:
            root_certs:
              filename: /etc/pki/tls/cert.pem
        credentials_factory_name: envoy.grpc_credentials.aws_iam
        call_credentials:
          from_plugin:
            name: envoy.grpc_credentials.aws_iam
            config:
              region: us-east-1
              service_name: appmesh
  lds_config: {ads: {}}
  cds_config: {ads: {}}
tracing:
  http:
    name: envoy.tracers.datadog
    config:
      collector_cluster: datadog_agent
      service_name: envoy
static_resources:
  clusters:
  - name: datadog_agent
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: dd-agent.prod.svc.cluster.local
        port_value: 8126
```

So I don't seem to be using the same pattern as the doc. 
Have you tried adding the listener part in the additional conf file ?
